// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import en_US from './en-US'
import fr from './fr'

import en_US_authentication from './en-US/authentication'
import en_US_guards from './en-US/guards'
import fr_authentication from './fr/authentication'
import fr_guards from './fr/guards'

const localeTranslations = {
	'en-US': {
		...en_US,
		authentication: en_US_authentication,
		guards: en_US_guards
	},
	fr: {
		...fr,
		authentication: fr_authentication,
		guards: fr_guards
	},
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
